"""Shared constants for the compliance capsule engine."""

from __future__ import annotations

from pathlib import Path

COLLECTION_ANALYTICAL = "analytical_capsules"
COLLECTION_SCHEMA = "schema_context_capsules"
COLLECTION_LINKED = "linked_capsules"
ALL_COLLECTIONS = [COLLECTION_ANALYTICAL, COLLECTION_SCHEMA, COLLECTION_LINKED]

EMBED_DIM = 384
EMBED_MODEL_DEFAULT = "BAAI/bge-small-en-v1.5"

CAPSULE_TYPE_AGGREGATION = "aggregation"
CAPSULE_TYPE_TREND = "trend"
CAPSULE_TYPE_VIOLATION = "violation"
CAPSULE_TYPE_PATTERN = "pattern"
CAPSULE_TYPE_RISK = "risk"
CAPSULE_TYPE_OPERATIONAL = "operational"
CAPSULE_TYPE_DISTRIBUTION = "distribution"
CAPSULE_TYPE_LINKED = "linked"
CAPSULE_TYPE_SAMPLE = "sample"

PRIORITY_P1 = "P1"
PRIORITY_P2 = "P2"
PRIORITY_P3 = "P3"
PRIORITY_P4 = "P4"

INTENT_STRUCTURED = "structured"
INTENT_ANALYTICAL = "analytical"
INTENT_HYBRID = "hybrid"
INTENT_OPERATIONAL = "operational"

ANALYTICAL_TOP_K = 5
SCHEMA_TOP_K = 5
LINKED_TOP_K = 5
ANALYTICAL_MIN_SCORE = 0.30
SCHEMA_MIN_SCORE = 0.20
LINKED_MIN_SCORE = 0.25
CONFIDENCE_THRESHOLD_CAPSULE_ANSWER = 0.65

ANOMALY_STDDEV_MULTIPLIER = 2.0
ANOMALY_DETECTED_THRESHOLD = 0.7
TREND_CHANGE_PCT = 10.0

MAX_HOP_DEPTH = 2
MAX_LINKED_CAPSULES = 3
MIN_SHARED_TAGS_FOR_RELATION = 2

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
ANALYTICAL_REFRESH_PLAN_FILE = DATA_DIR / ".analytical_refresh_plan.json"
SCHEMA_FINGERPRINT_FILE = DATA_DIR / ".schema_fingerprint.json"
CAPSULE_GRAPH_FILE = DATA_DIR / ".capsule_graph.json"
DATA_FINGERPRINT_FILE = DATA_DIR / ".data_fingerprint.json"

DB_MAX_RETRIES = 3
DB_MAX_POOL = 10
DB_EXECUTE_MAX_ROWS = 500
CAPSULE_RESULT_MAX_ROWS = 50

UI_MAX_HISTORY = 5
UI_MAX_CAPSULE_ROWS = 500

REL_CORROBORATES = "corroborates"
REL_DRILLS_DOWN = "drills_down"
REL_AGGREGATES_UP = "aggregates_up"
REL_SAME_ENTITY = "same_entity"

TAG_ANOMALY = "anomaly_detected"
TAG_ESCALATING = "escalating_risk"

VIOLATION_TYPES = [CAPSULE_TYPE_VIOLATION, CAPSULE_TYPE_RISK]

