# File: src/text_to_sql.py
"""Convert user text into deterministic SQL queries."""

from __future__ import annotations

import json
import os
import re
from typing import Any
from urllib import error, request

from .app_constants import (
    ALLOWED_TABLES,
    DEFAULT_GROQ_MODEL,
    DEFAULT_SQL_MAX_OUTPUT_TOKENS,
    DEFAULT_USER_AGENT,
    GROQ_RESPONSES_API_URL,
    HTTP_DEFAULT_TIMEOUT_SECONDS,
    SQL_FALLBACK_TOP_N,
    TEMPERATURE_ZERO,
)
from .database_connection import get_foreign_keys, get_schema_metadata


def generate_sql_from_question(user_query: str) -> dict[str, str]:
    """Generate safe SQL for structured queries."""
    schema = get_schema_metadata()
    relationships = get_foreign_keys()
    generated = _generate_sql_with_groq(user_query, schema, relationships)
    if generated:
        return generated
    return _generate_sql_fallback(user_query)


def _generate_sql_with_groq(
    user_query: str,
    schema: dict[str, list[dict[str, str]]],
    relationships: list[str],
) -> dict[str, str] | None:
    api_key = os.getenv("GROQ_API_KEY")
    debug = os.getenv("SQL_DEBUG", "").strip().lower() in {"1", "true", "yes", "on"}
    if debug:
        print("Groq key present:", bool(api_key))
    if not api_key:
        return None

    model = os.getenv("GROQ_SQL_MODEL", DEFAULT_GROQ_MODEL)
    if debug:
        print("\n=== SQL GENERATION DEBUG ===")
        print("User Query:", user_query)
        print("Model:", model)
    schema_text = _schema_to_text(schema)
    relationships_text = _relationships_to_text(relationships)
    prompt = (
        "Database schema\n"
        "---------------\n"
        f"{schema_text}\n\n"
        "Relationships\n"
        "-------------\n"
        f"{relationships_text}\n\n"
        "Instructions\n"
        "------------\n"
        "Generate one SQL Server SELECT query answering the user's question.\n"
        "Rules for SQL generation:\n"
        "1. Use only tables and columns present in the schema.\n"
        "2. If ranking entities, use aggregation functions like COUNT, SUM, or AVG with GROUP BY.\n"
        "3. Use JOINs when data from multiple tables is required.\n"
        "4. Prefer human-readable columns (e.g., names or labels) rather than numeric IDs in output.\n"
        "5. Return exactly one SELECT statement with no semicolon.\n\n"
        "Return strict JSON with keys: query_plan, sql, reason.\n\n"
        f"User question: {user_query}\n"
    )

    payload: dict[str, Any] = {
        "model": model,
        "temperature": TEMPERATURE_ZERO,
        "max_output_tokens": DEFAULT_SQL_MAX_OUTPUT_TOKENS,
        "input": [
            {
                "role": "system",
                "content": (
                    "Generate safe, deterministic SQL Server SELECT queries.\n"
                    "Do not call tools.\n"
                    "Do not execute code.\n"
                    "Return only JSON containing SQL."
                ),
            },
            {"role": "user", "content": prompt},
        ],
    }

    req = request.Request(
        url=GROQ_RESPONSES_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": DEFAULT_USER_AGENT,
        },
        method="POST",
    )

    try:
        with request.urlopen(req, timeout=HTTP_DEFAULT_TIMEOUT_SECONDS) as resp:
            body = json.loads(resp.read().decode("utf-8"))
            if debug:
                print("\nRAW LLM RESPONSE:")
                print(json.dumps(body, indent=2, default=str))
                print()
            message = _extract_response_text(body)
            if debug:
                print("\nLLM Raw Response:")
                print(message)
                print()
            cleaned = _clean_llm_json(message)
            parsed = json.loads(cleaned)
    except (error.URLError, error.HTTPError, TimeoutError, KeyError) as exc:
        if debug:
            print("LLM request/parsing failed before JSON decode:", exc)
            print("============================\n")
        return None
    except ValueError as exc:
        if debug:
            print("LLM output is not valid JSON:", exc)
            print("============================\n")
        return None

    sql = str(parsed.get("sql", "")).strip()
    reason = str(parsed.get("reason", "Generated by Groq SQL model.")).strip()
    query_plan = str(parsed.get("query_plan", "")).strip()

    if debug:
        print("\nParsed SQL:")
        print(sql)
        print("============================\n")

    if not _is_safe_sql(sql):
        if debug:
            print("SQL rejected by safety validator:", sql)
            print(sql)
        return None

    final_reason = reason or "Generated by Groq SQL model."
    if query_plan:
        final_reason = f"{final_reason} Plan: {query_plan}"
    return {"sql": sql, "reason": final_reason}


def _generate_sql_fallback(user_query: str) -> dict[str, str]:
    table = next(iter(ALLOWED_TABLES), "")
    if table:
        return {
            "sql": f"SELECT TOP {SQL_FALLBACK_TOP_N} * FROM {table}",
            "reason": "Fallback generic query when LLM generation fails.",
        }
    return {
        "sql": f"SELECT TOP {SQL_FALLBACK_TOP_N} TABLE_NAME FROM INFORMATION_SCHEMA.TABLES",
        "reason": "Fallback placeholder query when LLM generation fails.",
    }


def _schema_to_text(schema: dict[str, list[dict[str, str]]]) -> str:
    lines: list[str] = []
    for table_name, columns in schema.items():
        col_text = ", ".join(f"{col['name']} ({col['type']})" for col in columns)
        lines.append(f"{table_name}: {col_text}")
    return "\n".join(lines)


def _relationships_to_text(relationships: list[str]) -> str:
    if not relationships:
        return "None"
    return "\n".join(relationships)


def _is_safe_sql(sql: str) -> bool:
    normalized = re.sub(r"\s+", " ", sql.strip().lower())
    if not normalized.startswith("select "):
        return False
    if ";" in normalized:
        return False
    banned = (
        "insert ",
        "update ",
        "delete ",
        "drop ",
        "alter ",
        "create ",
        "merge ",
        "exec ",
        " union ",
    )
    if any(token in normalized for token in banned):
        return False
    referenced_tables = {
        t.lower()
        for t in re.findall(
            r"\b(?:from|join)\s+(?:\w+\.)?(?:\w+\.)?([a-zA-Z_][\w]*)",
            normalized,
        )
    }
    allowed = {t.lower() for t in ALLOWED_TABLES}
    return referenced_tables.issubset(allowed) if referenced_tables else True


def _extract_response_text(body: dict[str, Any]) -> str:
    """Extract assistant text from Groq/OpenAI response formats."""
    if "output" in body:
        for item in body["output"]:
            if not isinstance(item, dict):
                continue
            if item.get("type") == "message":
                content = item.get("content", [])
                if not isinstance(content, list):
                    continue
                for part in content:
                    if not isinstance(part, dict):
                        continue
                    if part.get("type") in ("output_text", "text"):
                        return str(part.get("text", ""))

    if "output_text" in body:
        return str(body["output_text"])

    if "choices" in body:
        return str(body["choices"][0]["message"]["content"])

    raise ValueError(f"Unsupported response structure: {body}")


def _clean_llm_json(text: str) -> str:
    """Remove markdown code fences and return pure JSON string."""
    text = text.strip()

    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines)

    return text.strip()
